"""Phase 11 — Create the final data room.

Reads the boss-edited Excel guide. For every row marked `include` or
`include_after_redaction`, copies (never moves) the source file to the
target folder under the deal-type taxonomy, with the renamed filename.

`include_after_redaction` rows require either:
- a populated `redacted_file_path` column, OR
- explicit `--allow-unredacted-override <file_id>` argument.

Never auto-redacts. Never modifies originals. Never auto-uploads.

Writes:
- <DataRoomName>_Index_<YYYY-MM-DD>.xlsx (buyer-facing index, only included rows)
- creation_log.csv
- PERMISSIONS_CHECKLIST.md
"""

from __future__ import annotations

import argparse
import csv
import datetime as _dt
import shutil
import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).parent))
import utils  # noqa: E402
from validate_guide import find_run_dir_for_guide, load_workbook_data  # noqa: E402

INCLUDE_DECISIONS = {"include", "include_after_redaction"}


def collision_safe_path(target: Path) -> Path:
    """Append _v2, _v3, ... if `target` already exists."""
    if not target.exists():
        return target
    stem, suffix = target.stem, target.suffix
    for v in range(2, 100):
        candidate = target.with_name(f"{stem}_v{v}{suffix}")
        if not candidate.exists():
            return candidate
    raise RuntimeError(f"Too many collisions for {target} — investigate manually.")


def resolve_target_path(
    target_root: Path,
    proposed_room_path: str,
    proposed_renamed_filename: str,
) -> Path:
    """Build the absolute path inside target_root."""
    relative_dir = Path(proposed_room_path) if proposed_room_path else Path("")
    return collision_safe_path(target_root / relative_dir / proposed_renamed_filename)


def write_permissions_checklist(
    target_root: Path,
    *,
    deal_type: str,
    data_room_name: str,
    file_count: int,
) -> None:
    md = f"""# PERMISSIONS CHECKLIST — {data_room_name}

Generated by `acos-dataroom create-room` on {_dt.datetime.utcnow().isoformat()}Z.

**Deal type:** {deal_type}
**Files copied:** {file_count}

## Before sharing

- [ ] Confirm folder permissions on this directory allow only the intended audience.
- [ ] If this folder is in Dropbox, verify sharing settings in the Dropbox UI. The skill never sets sharing permissions.
- [ ] If buyers should be able to download (not just stream), ensure the folder is set to "Available offline" in Dropbox before sharing the link.
- [ ] Review the sensitivity log in the original Data Room Guide. Confirm any `include_after_redaction` rows have redacted versions in place.
- [ ] Confirm no `internal_only_*` files were inadvertently included.

## After sharing

- [ ] Note the date and counterparty in your engagement records.
- [ ] If this is a foreclosure auction, retain a backup copy of the procedural compliance file as the source of truth.
- [ ] If a counterparty disputes a document, the evidence bundle (in the run directory, NOT in this data room) is the audit trail.

## What this skill does NOT do

- Authenticate with Dropbox / Google / OneDrive / Box APIs.
- Generate sharing links.
- Set file or folder permissions.
- Send notifications to counterparties.
- Upload to a virtual data room platform.

Anything cloud-related happens outside this skill.
"""
    (target_root / "PERMISSIONS_CHECKLIST.md").write_text(md, encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Create the final data room.")
    parser.add_argument("--guide", required=True, type=Path)
    parser.add_argument("--target", required=True, type=Path)
    parser.add_argument("--confirmed", default="false")
    parser.add_argument("--allow-unredacted-override", action="append", default=[])
    parser.add_argument("--allow-non-empty-target", default="false")
    parser.add_argument("--data-room-name", default=None)
    parser.add_argument("--deal-type", default=None)
    args = parser.parse_args(argv)

    if str(args.confirmed).lower() != "true":
        print("--confirmed true is REQUIRED. The skill will not copy any file without it.")
        print()
        print("Confirmation checklist:")
        print("  - You have reviewed the Excel guide.")
        print("  - You have verified the include_after_redaction rows have redacted_file_path values.")
        print("  - The --target folder is empty (or you've passed --allow-non-empty-target true).")
        print("  - You're ready for files to be copied to --target.")
        return 1

    if not args.guide.exists():
        print(f"Guide not found: {args.guide}", file=sys.stderr)
        return 2

    args.target.mkdir(parents=True, exist_ok=True)
    if any(args.target.iterdir()) and str(args.allow_non_empty_target).lower() != "true":
        print(f"Target {args.target} is not empty. Pass --allow-non-empty-target true to overlay.", file=sys.stderr)
        return 2

    run_dir = find_run_dir_for_guide(args.guide)
    layout = {"base": run_dir, "logs": run_dir / "logs",
              "extraction": run_dir / "extraction",
              "evidence": run_dir / "evidence",
              "intermediate": run_dir / "intermediate"}
    utils.ensure_run_dirs(layout)
    logger = utils.make_logger(layout)

    # The new workbook design has 'Files Included' (rows to copy) and 'Files Excluded'.
    # Anything in 'Files Included' is a copy candidate.
    edited = load_workbook_data(args.guide)
    index_rows = edited.get("Files Included", [])

    # We need a way to map Original Filename → source_path. Pull this from the
    # original classifications.json which has both file_name and source path
    # info via the file_manifest.
    inter = run_dir / "intermediate"
    classifications_path = inter / "classifications.json"
    manifest_path = inter / "file_manifest.json"
    classifications = utils.read_json(classifications_path) if classifications_path.exists() else []
    manifest = utils.read_json(manifest_path) if manifest_path.exists() else {}
    name_to_source: dict[str, str] = {}
    for f in manifest.get("files", []):
        name_to_source[f.get("file_name", "")] = f.get("source_path", "")
    name_to_file_id: dict[str, str] = {c.get("file_name", ""): c.get("file_id", "") for c in classifications}

    # The 'Files Included' worksheet carries no decision/redaction column, so we
    # join each row back to its classification record to recover the
    # external_room_recommendation decision and the redaction signal. This is the
    # gate that enforces the invariant: a file marked for redaction must NEVER be
    # copied unredacted unless the user passes --allow-unredacted-override.
    def _decision_value(c: dict) -> str:
        """external_room_recommendation may be a bare string or a {value, reasoning} dict."""
        rec = c.get("external_room_recommendation")
        if isinstance(rec, dict):
            rec = rec.get("value", "")
        return (rec or "").strip().lower()

    name_to_decision: dict[str, str] = {}
    name_to_redaction: dict[str, dict] = {}
    for c in classifications:
        nm = c.get("file_name", "")
        name_to_decision[nm] = _decision_value(c)
        sens = c.get("sensitivity") or {}
        name_to_redaction[nm] = {
            "recommended": bool(sens.get("redaction_recommended")),
            "redacted_file_path": (c.get("redacted_file_path")
                                   or sens.get("redacted_file_path") or ""),
        }

    # Normalize the override list (callers may pass file ids or original filenames).
    override_ids = {str(o).strip() for o in (args.allow_unredacted_override or []) if str(o).strip()}

    to_copy = []
    skipped = []
    for row in index_rows:
        original = row.get("Original Filename") or ""
        if not original:
            continue
        source_path = name_to_source.get(original, "")
        file_id = name_to_file_id.get(original, "")

        # --- Decision gate ----------------------------------------------------
        # If we can resolve a decision for this row, honor it. Rows whose decision
        # is internal_only_*/superseded/absent must never be copied. (The internal
        # workbook normally pre-filters these out, but we re-check defensively in
        # case the boss hand-edited a row into 'Files Included'.)
        decision = name_to_decision.get(original, "")
        if decision and (decision.startswith("internal_only_")
                         or decision in ("superseded", "absent")):
            logger.warning("Row %s has decision %r — not an include decision; skipping.",
                           original, decision)
            skipped.append((original, f"decision_{decision}"))
            continue
        if decision and decision not in INCLUDE_DECISIONS:
            logger.warning("Row %s has unrecognized decision %r — skipping.",
                           original, decision)
            skipped.append((original, f"decision_{decision}"))
            continue

        # --- Redaction gate ---------------------------------------------------
        # A file marked for redaction (decision == include_after_redaction, or the
        # sensitivity record flags redaction_recommended) must NOT be copied
        # unredacted. Require either a redacted_file_path or an explicit override.
        redaction = name_to_redaction.get(original, {})
        needs_redaction = (decision == "include_after_redaction"
                           or redaction.get("recommended"))
        if needs_redaction:
            redacted_path = (row.get("Redacted File Path")
                             or redaction.get("redacted_file_path") or "")
            overridden = (original in override_ids) or (file_id and file_id in override_ids)
            if redacted_path:
                # Copy the redacted version instead of the original.
                source_path = redacted_path
            elif overridden:
                logger.warning("Row %s marked for redaction but copied UNREDACTED "
                               "via --allow-unredacted-override.", original)
            else:
                logger.warning("Row %s marked for redaction but has no redacted file "
                               "path and no --allow-unredacted-override; skipping.",
                               original)
                skipped.append((original, "redaction_required"))
                continue

        if not source_path:
            logger.warning("No source path for %s — skipping", original)
            skipped.append((original, "source_missing"))
            continue
        row["_source_for_copy"] = source_path
        row["_file_id"] = file_id
        row["_original"] = original
        to_copy.append(row)

    creation_log: list[dict[str, Any]] = []
    for row in to_copy:
        src = Path(row["_source_for_copy"]) if row["_source_for_copy"] else None
        if not src or not src.exists():
            logger.error("Source file for %s not found: %s", row["_original"], src)
            creation_log.append({
                "file_id": row["_file_id"],
                "original_filename": row["_original"],
                "source_path": str(src) if src else "",
                "target_path": "",
                "result": "source_missing",
            })
            continue

        # Build proposed_room_path from the 3 folder columns (handle visual-grouping suppression)
        primary = row.get("Primary Subfolder") or ""
        sub = row.get("Sub-folder") or ""
        subsub = row.get("Sub-sub-folder") or ""
        # Reverse the humanized form back to filesystem-safe folder names
        room_path_parts = []
        for part in (primary, sub, subsub):
            if part and part.strip():
                # Convert "01 — Default & NOD" -> "01_Default_and_NOD"
                fs_safe = part.replace(" — ", "_").replace(" & ", "_and_").replace(" ", "_")
                room_path_parts.append(fs_safe)
        room_path = "/".join(room_path_parts)

        renamed = row.get("Proposed Renamed Filename") or src.name

        dest = resolve_target_path(args.target, room_path, renamed)
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(str(src), str(dest))
        creation_log.append({
            "file_id": row["_file_id"],
            "original_filename": row["_original"],
            "source_path": str(src),
            "target_path": str(dest),
            "result": "copied",
        })
        logger.info("Copied %s -> %s", src.name, dest)

    # Write creation log CSV
    log_csv = args.target / "creation_log.csv"
    if creation_log:
        with open(log_csv, "w", newline="", encoding="utf-8") as fh:
            writer = csv.DictWriter(fh, fieldnames=list(creation_log[0].keys()))
            writer.writeheader()
            writer.writerows(creation_log)

    # Build buyer-facing index from the boss-finalized internal workbook.
    # build_buyer_workbook is the only path — if it raises, surface and abort
    # rather than producing a malformed index against the old column schema.
    from build_buyer_index import build_buyer_workbook
    final_index = build_buyer_workbook(
        args.guide,
        data_room_name=args.data_room_name or args.target.name,
        deal_type=args.deal_type or "unspecified",
        objective="Data room",
        output_dir=args.target,
    )

    write_permissions_checklist(
        args.target,
        deal_type=args.deal_type or "unspecified",
        data_room_name=args.data_room_name or args.target.name,
        file_count=sum(1 for r in creation_log if r["result"] == "copied"),
    )

    print(f"Data room created at: {args.target}")
    print(f"  Files copied: {sum(1 for r in creation_log if r['result'] == 'copied')}")
    print(f"  Files skipped: {len(skipped)}")
    print(f"  Final index: {final_index}")
    print(f"  Permissions checklist: {args.target / 'PERMISSIONS_CHECKLIST.md'}")

    utils.mark_phase_complete(layout, "phase_11_create_room", extra={
        "target": str(args.target),
        "copied": sum(1 for r in creation_log if r["result"] == "copied"),
        "skipped": len(skipped),
    })
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
