#!/usr/bin/env bun
// Bridge: preeng task files -> ACOS slice.yaml skeletons.
//
// Reads stories.json + tasks/<id>.md and emits planning/slices/<id>.yaml.
// Preeng slice ids are carried verbatim: this project already has O31/O32/O33/O34
// and A91+ id collisions, so a second numbering scheme would add to that problem.
//
// Nothing here invents an acceptance criterion. A field the task file does not
// support is emitted as `# TODO: confirm` so the gap stays visible.

const FEATURE = "/Users/zee/Documents/Vibe Coding/ACOS 3.0/Website Builder/planning/preeng/001-website-builder";
const OUT = "/Users/zee/Documents/Vibe Coding/ACOS 3.0/Website Builder/planning/slices";
const CREATED = "2026-07-26";

type Slice = {
  id: string; epic: string; story: string; title: string; type: string;
  moscow: string; size_class: string; objective: string; depends_on: string[];
  fr_ids: string[]; acceptance_criteria: string[]; demo?: unknown; cqs: string[];
  evidence_refs: string[]; blocking?: unknown; task_file?: string;
};

const q = (s: string) => `"${String(s ?? "").replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
const block = (s: string, indent = "  ") =>
  String(s ?? "").trim().split("\n").map((l) => indent + l).join("\n");

/** Pull the bullet lines under a bolded label, up to the next bold label or heading. */
function section(md: string, label: string): string[] {
  const re = new RegExp(`\\*\\*${label}[^*]*\\*\\*\\s*\\n?`, "i");
  const m = md.match(re);
  if (!m || m.index === undefined) return [];
  const rest = md.slice(m.index + m[0].length);
  const end = rest.search(/\n\*\*[A-Z]|\n## /);
  const body = end === -1 ? rest : rest.slice(0, end);
  return body.split("\n").map((l) => l.trim())
    .filter((l) => l.startsWith("- ") || /^\d+\./.test(l))
    .map((l) => l.replace(/^- /, "").replace(/^\d+\.\s*/, "").trim())
    .filter(Boolean);
}

/** The authoritative mapping line every task file carries. */
function mapping(md: string): { criteria: string[]; method: string } {
  const line = md.split("\n").find((l) => l.includes("slice.yaml") && l.includes("mapping"));
  if (!line) return { criteria: [], method: "" };
  const crit = line.match(/acceptance_criteria:\s*\[([^\]]*)\]/);
  const meth = line.match(/verification_method:\s*`?([a-z-]+)`?/);
  return {
    criteria: crit ? crit[1].split(",").map((s) => s.trim()).filter(Boolean) : [],
    method: meth ? meth[1] : "",
  };
}

const stories = JSON.parse(await Bun.file(`${FEATURE}/stories.json`).text());
const slices: Slice[] = stories.slices ?? [];
const storyTitle = Object.fromEntries((stories.stories ?? []).map((s: any) => [s.id, s.title ?? s.name ?? ""]));
const epicTitle = Object.fromEntries((stories.epics ?? []).map((e: any) => [e.id, e.title ?? e.name ?? ""]));

await Bun.$`mkdir -p ${OUT}`.quiet();

const problems: string[] = [];
let written = 0;

for (const s of slices) {
  const path = `${FEATURE}/tasks/${s.id}.md`;
  const f = Bun.file(path);
  if (!(await f.exists())) { problems.push(`${s.id}: task file missing`); continue; }
  const md = await f.text();

  // A bullet may mix an allowance and a prohibition in one line, so split at
  // sentence level: a sentence opening with "No ..." is a prohibition, the rest
  // is an allowance. Classifying whole bullets loses the allowance (S28).
  const allowed: string[] = [];
  const prohibited: string[] = [];
  for (const bullet of section(md, "Allowed files")) {
    for (const raw of bullet.split(/(?<=\.)\s+(?=\**[A-Z])/)) {
      const sentence = raw.trim();
      if (!sentence) continue;
      (/^\**No\b/i.test(sentence) ? prohibited : allowed).push(sentence);
    }
  }
  const dod = section(md, "Definition of Done");
  const { criteria, method } = mapping(md);

  if (!allowed.length) problems.push(`${s.id}: no allowed-files entries parsed`);
  if (!criteria.length) problems.push(`${s.id}: no acceptance_criteria ids parsed`);
  if (!method) problems.push(`${s.id}: no verification_method parsed`);

  const effort = ({ S: "S", M: "M", L: "L" } as Record<string, string>)[s.size_class] ?? "M";

  const yaml = `# Generated by _bridge-to-slices.ts from preeng feature 001-website-builder.
# Source of truth for this slice: planning/preeng/001-website-builder/tasks/${s.id}.md
# Preeng ids are carried verbatim — do not renumber.

slice_id: ${q(s.id)}
story_id: ${q(s.story)}          # ${storyTitle[s.story] ?? ""}
epic_id: ${q(s.epic)}            # ${epicTitle[s.epic] ?? ""}
vision_id: "VISION-WEBSITE-BUILDER"
created_date: ${q(CREATED)}
created_by: acos-preeng-classic-bridge
status: "planned"

title: ${q(s.title)}
objective: |
${block(s.objective || "# TODO: confirm — stories.json carried no objective")}

# Ids come from the task file's own slice.yaml mapping line; the statements
# come from its Definition of Done. Nothing here is invented.
acceptance_criteria:
${criteria.length ? criteria.map((c) => `  - ${q("[ ] " + c)}`).join("\n") : `  - ${q("[ ] # TODO: confirm — no criterion ids in the task file")}`}
${dod.length ? dod.map((d) => `  - ${q("[ ] " + d)}`).join("\n") : `  - ${q("[ ] # TODO: confirm — no Definition of Done parsed")}`}

verification_method: ${q(method || "# TODO: confirm")}

dependencies:
  slices:
${(s.depends_on ?? []).length
    ? (s.depends_on ?? []).map((d) => `    - slice_id: ${q(d)}\n      what_it_provides: "# TODO: confirm — see the task file's In scope"\n      status: "planned"`).join("\n")
    : "    []"}

files_allowed:
${allowed.length ? allowed.map((a) => `  - ${q(a)}`).join("\n") : `  - ${q("# TODO: confirm — no allowed-files list parsed")}`}

files_prohibited:
${prohibited.length ? prohibited.map((p) => `  - ${q(p)}`).join("\n") : "  []"}

flow: "slice-execution-flow"

effort_estimate: ${q(effort)}

assigned_to: null
assigned_date: null
handoff_path: null

# Traceability — every id below resolves into the preeng artifact set.
traceability:
  type: ${q(s.type)}
  moscow: ${q(s.moscow)}
  fr_ids: [${(s.fr_ids ?? []).map(q).join(", ")}]
  cqs: [${(s.cqs ?? []).map(q).join(", ")}]
  evidence_refs: [${(s.evidence_refs ?? []).map(q).join(", ")}]
  source_task_file: ${q(`planning/preeng/001-website-builder/tasks/${s.id}.md`)}

notes: |
  Read the source task file before starting — it carries the PM / Dev / QA
  contract in full, including the seven-part evidence bundle and the zero-trust
  QA steps this skeleton only summarises.
  Role charters: planning/preeng/001-website-builder/agent_instructions/{pm,dev,qa}.md
  BUILD GATE: §18 admits no v1 build slice until its sign-off rows are resolved.
  Four remain unsigned — 4(c) rich-text-is-v2, 4(d) one-direction-only, 4(f)
  editor-lacks-zoom-pan-rulers-multi-select, 6 charts-partial.
`;

  await Bun.write(`${OUT}/${s.id}.yaml`, yaml);
  written++;
}

console.log(`slices written: ${written}/${slices.length} -> ${OUT}`);
console.log(problems.length ? `PARSE GAPS (${problems.length}):\n  ${problems.join("\n  ")}` : "PARSE GAPS: none");
