"""Generate Manual_Review_Required_<date>.md from acos-dataroom-v2 run state.

Aggregates the various manual-review buckets and emits a single operator-facing
markdown listing files that need follow-up:
  - Encrypted / password-protected
  - Zero-byte
  - Unsupported extension / oversized
  - Phase 2 disputed (K=5 inclusion deliberation exhausted)
  - Phase 3 QA-failed unconverged
  - Phase 5 QA-failed unconverged
  - Phase 4b pending classification (lands in 00_Pending_Classification/)
  - Phase 2.5 privilege-removed (informational — these are CORRECTLY removed)

Only writes the file if at least one bucket is non-empty. If all empty, prints
"NO_MANUAL_REVIEW_NEEDED" to stdout and writes nothing.

CLI usage:
  python3 build_manual_review_md.py --run-dir <RUN_DIR> --output <PATH>
"""
from __future__ import annotations

import argparse
import csv
import datetime as _dt
import json
import sys
from pathlib import Path
from typing import Any


def _read_csv_safe(p: Path) -> list[dict[str, str]]:
    if not p.exists():
        return []
    rows = []
    try:
        with p.open("r", encoding="utf-8") as f:
            reader = csv.DictReader(f)
            for r in reader:
                rows.append(r)
    except Exception:
        pass
    return rows


def _read_dir_jsons(d: Path) -> list[dict[str, Any]]:
    if not d.exists():
        return []
    out = []
    for fp in sorted(d.glob("*.json")):
        try:
            with fp.open("r", encoding="utf-8") as f:
                out.append(json.load(f))
        except Exception:
            pass
    return out


def gather_buckets(run_dir: Path) -> dict[str, list[Any]]:
    return {
        "unable_to_evaluate": _read_csv_safe(run_dir / "intermediate" / "unable_to_evaluate.csv"),
        "phase2_disputed": _read_dir_jsons(run_dir / "phase2" / "disputed"),
        "phase2_5_privileged_removed": _read_csv_safe(run_dir / "phase2_5" / "privileged_removed.csv"),
        "phase3_unconverged": _read_csv_safe(run_dir / "phase3" / "qa_failed_unconverged.csv"),
        "phase4_pending": _read_csv_safe(run_dir / "phase4" / "placement_pending.csv"),
        "phase5_unconverged": _read_csv_safe(run_dir / "phase5" / "qa_failed_unconverged.csv"),
    }


def build_markdown(run_dir: Path, output: Path) -> Path | None:
    buckets = gather_buckets(run_dir)
    total = sum(len(v) for v in buckets.values())
    # Exclude privilege-removed from "needs review" total since those are correctly removed
    actionable = total - len(buckets["phase2_5_privileged_removed"])

    if actionable == 0 and len(buckets["phase2_5_privileged_removed"]) == 0:
        return None

    lines = []
    today = _dt.date.today().isoformat()
    lines.append(f"# Manual Review Required — {today}")
    lines.append("")
    lines.append(f"**Run directory:** `{run_dir}`")
    lines.append("")
    lines.append(
        "This file is generated by acos-dataroom-v2 when one or more buckets need "
        "operator (Zee) follow-up. **Not a buyer-facing artifact** — do not include "
        "in the data room shipped to the counterparty."
    )
    lines.append("")
    lines.append(f"**Total files needing action:** {actionable}")
    lines.append(f"**Files correctly removed (privilege):** {len(buckets['phase2_5_privileged_removed'])} (informational only)")
    lines.append("")

    sections = [
        ("unable_to_evaluate", "Files that could not be evaluated (encrypted / zero-byte / oversized / unsupported)",
         "These files were pre-bucketed before reaching the deliberation swarm. Encrypted "
         "PDFs need a password to extract; zero-byte files are empty; oversized files "
         "exceeded the 50 MB token-cost cap. Action: open each manually, decide whether it "
         "belongs in the dataroom, and either redact + re-add or exclude."),
        ("phase2_disputed", "Files with unresolved Phase 2 inclusion disputes (K=5 exhausted)",
         "The 3 deliberation agents could not reach unanimous consensus after 5 blind "
         "re-dispatches. The skill's default-EXCLUDE rule kept these out of the dataroom. "
         "Action: review the deliberation trail for each (see phase2/disputed/<file_id>.json) "
         "and decide whether to manually include."),
        ("phase3_unconverged", "Files that failed Phase 3 QA after K=5 iterations",
         "The QA Wigum loop could not stabilize on these files. They were excluded from the "
         "final dataroom. Action: review each manually to decide inclusion."),
        ("phase4_pending", "Files placed in 00_Pending_Classification/ (Phase 4b unanimity failed)",
         "The 3 placement agents disagreed on sub-folder after 5 re-dispatches. Files are "
         "in dataroom/00_Pending_Classification/. Action: manually move each into the "
         "appropriate numbered sub-folder."),
        ("phase5_unconverged", "Files that failed Phase 5 placement QA after K=5 iterations",
         "The placement Wigum loop could not stabilize. Files remain in whichever folder "
         "they last landed in. Action: manually verify placement."),
        ("phase2_5_privileged_removed", "Files removed by Phase 2.5 privilege scanner (informational)",
         "These files were FLAGGED for privilege by at least one scanner and removed under "
         "the asymmetric-consensus rule. They are NOT in the dataroom. Action (optional): "
         "review each scanner's reasoning if you disagree with the removal."),
    ]

    for key, heading, description in sections:
        items = buckets[key]
        if not items:
            continue
        lines.append(f"## {heading}")
        lines.append("")
        lines.append(description)
        lines.append("")
        lines.append("| Filename | Reason / Notes | Source path |")
        lines.append("|---|---|---|")
        for item in items:
            if isinstance(item, dict):
                fn = item.get("filename") or item.get("file") or item.get("file_id", "?")
                reason = item.get("reason") or item.get("notes") or item.get("triggered_markers") or ""
                src = item.get("source_path") or item.get("path", "")
                if isinstance(reason, list):
                    reason = "; ".join(str(x) for x in reason)
                lines.append(f"| `{fn}` | {reason} | `{src}` |")
            else:
                lines.append(f"| (unparseable record) | — | — |")
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("*acos-dataroom-v2 Manual Review Required — operator follow-up only. Not for buyer.*")

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines), encoding="utf-8")
    return output


def cli_main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Build acos-dataroom-v2 manual-review markdown.")
    parser.add_argument("--run-dir", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args(argv)

    if not args.run_dir.is_dir():
        print(f"ERROR: run-dir not found: {args.run_dir}", file=sys.stderr)
        return 2

    out = build_markdown(args.run_dir, args.output)
    if out is None:
        print("NO_MANUAL_REVIEW_NEEDED")
    else:
        print(str(out))
    return 0


if __name__ == "__main__":
    sys.exit(cli_main())
